name: flutter_lib_shared
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  # 屏幕适配


  flutter_screenutil: ^5.8.4


  # 图片轮播
  flutter_swiper_plus: ^2.0.4
  #图片网络缓存
  cached_network_image: ^3.2.3
  #提示
  fluttertoast: 8.0.8
  #路由管理
  get: 4.6.5
  uuid: 3.0.6
  sliver_tools: 0.2.7

  flutter_list_view: 1.1.18
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   : 2.1.0
  #日期选择
  flutter_pickers: 2.1.9
  #选择器
  flutter_picker: 2.1.0
  # wrap组件
  extended_wrap: 0.1.5
  # 复选框
  roundcheckbox: 2.0.4+1
  #网络请求
  dio: 5.0.1
  # 数据本地存储
  get_storage: 2.1.1
  #加载框
  flutter_easyloading:  3.0.5
  #下拉刷新
  pull_to_refresh: 2.0.0

  flutter_easyrefresh: 2.2.2
  # 常用工具类库
  common_utils: '>=2.0.2 <3.0.0'
  synchronized: '>=3.0.0 <5.0.0'
  #文件路径
  path_provider: '>=2.0.0 <4.0.0'
  #日志库
  logger: 1.2.2
  #滑动删除
  flutter_slidable: 2.0.0
  #圆形进度条
  percent_indicator: 4.2.2
  #多媒体选择组件
  image_picker: ^0.8.6+4
  video_thumbnail: 0.5.3

  #网络监听
  connectivity_plus: ^5.0.1

  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  #视频播放
  video_player: ^2.5.3
  #文件选择
  file_picker: ^5.2.4
  #打开url链接
  url_launcher: ^6.1.5
  #图片查看
  photo_view: ^0.14.0
  #webview
  webview_flutter: ^3.0.4
  #分享
  flutter_share: ^2.0.0
  #获取应用信息
  package_info_plus: ^3.0.3
  #App更新
  flutter_xupdate: ^3.0.0
  #屏幕旋转
  # auto_orientation: ^2.2.1
  #列表
  azlistview: ^2.0.0
  #获取中文首字母
  lpinyin: ^2.0.3



  #权限请求
  permission_handler: ^11.0.1
  flutter_localizations:
    sdk: flutter

  bs_flutter: 0.4.7
  #文件下载器
#  al_downloader: 1.5.7
#  dio_http_cache: 0.3.0

  extended_image: ^8.0.2

    # 极光推送 https://github.com/jpush/jpush-flutter-plugin
#  jpush_flutter: 2.4.0

  ele_progress: 0.0.1

#  tencent_kit: ^4.0.0

  fluwx: 3.12.2

  tobias: 2.4.1+1
  r_get_ip: 0.1.1
  get_ip_address: 0.0.5
  sp_util: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: generated
  # Optional. Sets whether utomatic monitoring of file changes. Default: true
  auto_detection: true
  # Optional. Sets file name conversion rules. Default: true
  named_with_parent: false
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: r
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: R